"""Add Product Intelligence models and ticket project_id

Revision ID: 58db9f6c147b
Revises: be16c0685dff
Create Date: 2026-02-17 15:21:49.926512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58db9f6c147b'
down_revision: Union[str, Sequence[str], None] = 'be16c0685dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('prompt_sent', sa.Text(), nullable=True),
    sa.Column('response_received', sa.Text(), nullable=True),
    sa.Column('is_valid_json', sa.Boolean(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_logs_id'), 'ai_analysis_logs', ['id'], unique=False)
    op.create_table('ai_roadmap_phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('epic_ids', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_roadmap_phases_id'), 'ai_roadmap_phases', ['id'], unique=False)
    op.create_table('prd_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prd_documents_id'), 'prd_documents', ['id'], unique=False)
    op.create_table('ai_epics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('prd_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT_AI_GENERATED', 'APPROVED', 'REJECTED', name='aistatus'), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prd_id'], ['prd_documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_epics_id'), 'ai_epics', ['id'], unique=False)
    op.create_table('ai_user_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('epic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT_AI_GENERATED', 'APPROVED', 'REJECTED', name='aistatus'), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['epic_id'], ['ai_epics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_user_stories_id'), 'ai_user_stories', ['id'], unique=False)
    op.add_column('tickets', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    
    # Backfill project_id for existing tickets
    # Use the identified project ID
    op.execute("UPDATE tickets SET project_id = '5d13484a-aad1-4342-b551-be9a6425905d' WHERE project_id IS NULL")
    
    # Now set it to NOT NULL
    op.alter_column('tickets', 'project_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'project_id')
    op.drop_index(op.f('ix_ai_user_stories_id'), table_name='ai_user_stories')
    op.drop_table('ai_user_stories')
    op.drop_index(op.f('ix_ai_epics_id'), table_name='ai_epics')
    op.drop_table('ai_epics')
    op.drop_index(op.f('ix_prd_documents_id'), table_name='prd_documents')
    op.drop_table('prd_documents')
    op.drop_index(op.f('ix_ai_roadmap_phases_id'), table_name='ai_roadmap_phases')
    op.drop_table('ai_roadmap_phases')
    op.drop_index(op.f('ix_ai_analysis_logs_id'), table_name='ai_analysis_logs')
    op.drop_table('ai_analysis_logs')
    # ### end Alembic commands ###
