"""Add standup sessions and enhanced fields

Revision ID: e000357afba3
Revises: 78186d52ce34
Create Date: 2026-02-17 00:22:00.188764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e000357afba3'
down_revision: Union[str, Sequence[str], None] = '78186d52ce34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standup_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['standup_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standup_sessions_id'), 'standup_sessions', ['id'], unique=False)
    op.add_column('standup_configs', sa.Column('time', sa.String(), nullable=True))
    op.add_column('standup_configs', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('standup_configs', sa.Column('working_days', sa.JSON(), nullable=True))
    op.add_column('standup_configs', sa.Column('response_window_hours', sa.Integer(), nullable=True))
    op.add_column('standup_responses', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('standup_responses', sa.Column('yesterday', sa.Text(), nullable=True))
    op.add_column('standup_responses', sa.Column('today', sa.Text(), nullable=True))
    op.add_column('standup_responses', sa.Column('blockers', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'standup_responses', 'standup_sessions', ['session_id'], ['id'])
    op.add_column('standup_summaries', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'standup_summaries', 'standup_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standup_summaries', type_='foreignkey')
    op.drop_column('standup_summaries', 'session_id')
    op.drop_constraint(None, 'standup_responses', type_='foreignkey')
    op.drop_column('standup_responses', 'blockers')
    op.drop_column('standup_responses', 'today')
    op.drop_column('standup_responses', 'yesterday')
    op.drop_column('standup_responses', 'session_id')
    op.drop_column('standup_configs', 'response_window_hours')
    op.drop_column('standup_configs', 'working_days')
    op.drop_column('standup_configs', 'timezone')
    op.drop_column('standup_configs', 'time')
    op.drop_index(op.f('ix_standup_sessions_id'), table_name='standup_sessions')
    op.drop_table('standup_sessions')
    # ### end Alembic commands ###
